env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
gomod:
  proxy: true
builds:
  - id: "win-lin"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    goamd64:
      - v3
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=pterm
  - id: "darwin"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v3
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=pterm

universal_binaries:
  - id: darwin
    name_template: '{{.ProjectName}}_{{.Version}}'
    replace: true
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^refactor'
      - Merge pull request
      - Merge branch
      - go mod tidy
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
      - "win-lin"
    files:
      - LICENSE
      - README.md
    replacements:
      linux: Linux
      windows: Windows
    format_overrides:
      - goos: windows
        format: zip
